// src/views/DashboardView.tsx
import React, { useState, useEffect, useCallback } from 'react';
import { 
  Bell, Coins, TrendingUp, TrendingDown, ArrowUpDown, Clock,
  ShoppingBag, Wallet, Settings, Megaphone, RefreshCw, AlertCircle
} from 'lucide-react';
import { ViewProps } from '../types';
import { Card, NeonButton, Badge, LoadingSpinner } from '../components';
import { 
  dashboardApi, 
  tradeApi,
  type TradeItem,
  type PlatformItem,
  type MerchantItem,
  type MemberItem,
  type TodayStats,
  type QuickAction
} from '../services/dashboardApi';

// 默认数据（用于API失败时的回退）
const DEFAULT_ASSET_BALANCE = 15000;
const DEFAULT_TODAY_STATS = {
  buy: 3200,
  sell: 1200,
  buyRate: '+5.2%',
  sellStatus: 'Active',
  transactionCount: 0,
  successRate: 0
};

const DashboardView: React.FC<ViewProps> = ({ navigate, t, lang, userInfo }) => {
  const [activeTab, setActiveTab] = useState<'platform' | 'merchant' | 'member'>('merchant'); 
  const [filterType, setFilterType] = useState<'all' | 'buy' | 'sell'>('all'); 
  const [sortType, setSortType] = useState<'time' | 'amount'>('time'); 
  const [sortDirection, setSortDirection] = useState<'asc' | 'desc'>('desc');
  
  // 状态管理
  const [loading, setLoading] = useState({
    dashboard: true,
    list: true,
    assets: true
  });
  const [error, setError] = useState<string | null>(null);
  
  // 数据状态
  const [assetBalance, setAssetBalance] = useState<number>(DEFAULT_ASSET_BALANCE);
  const [todayStats, setTodayStats] = useState<TodayStats>(DEFAULT_TODAY_STATS);
  const [platformList, setPlatformList] = useState<PlatformItem[]>([]);
  const [merchantList, setMerchantList] = useState<MerchantItem[]>([]);
  const [memberList, setMemberList] = useState<MemberItem[]>([]);
  const [quickActions, setQuickActions] = useState<QuickAction[]>([]);
  const [lastUpdated, setLastUpdated] = useState<string>('');

  // 获取仪表板数据
  const fetchDashboardData = useCallback(async () => {
    try {
      setLoading(prev => ({ ...prev, dashboard: true }));
      setError(null);
      
      // 并行请求关键数据
      const [assetsRes, statsRes, actionsRes] = await Promise.allSettled([
        dashboardApi.getUserAssets(),
        dashboardApi.getTodayStats(),
        dashboardApi.getQuickActions()
      ]);
      
      // 处理资产数据
      if (assetsRes.status === 'fulfilled' && assetsRes.value.data) {
        console.log(assetsRes.value.data.points.available ,assetsRes.value.data)
        setAssetBalance(assetsRes.value.data.points.available || DEFAULT_ASSET_BALANCE);
      } else {
        console.warn('Failed to load assets, using default');
      }
      
      // 处理今日统计
      if (statsRes.status === 'fulfilled' && statsRes.value.data) {
        setTodayStats(statsRes.value.data);
      } else {
        console.warn('Failed to load today stats, using default');
      }
      
      // 处理快速操作
      if (actionsRes.status === 'fulfilled' && actionsRes.value.data) {
        setQuickActions(actionsRes.value.data);
      }
      
      // 更新最后刷新时间
      setLastUpdated(new Date().toLocaleTimeString());
      
    } catch (err: any) {
      console.error('Failed to load dashboard data:', err);
      setError(t.dashboard.errors?.loadFailed || 'Failed to load dashboard data');
    } finally {
      setLoading(prev => ({ ...prev, dashboard: false }));
    }
  }, [t]);

  // 获取列表数据
  const fetchListData = useCallback(async () => {
    try {
      setLoading(prev => ({ ...prev, list: true }));
      
      const params = {
        filterType: filterType === 'all' ? undefined : filterType,
        sortType,
        sortDirection
      };
      
      let response;
      switch (activeTab) {
        case 'platform':
          response = await dashboardApi.getPlatformList(params);
          if (response.data) setPlatformList(response.data);
          break;
        case 'merchant':
          response = await dashboardApi.getMerchantList(params);
          if (response.data) setMerchantList(response.data);
          break;
        case 'member':
          response = await dashboardApi.getMemberList(params);
          if (response.data) setMemberList(response.data);
          break;
      }
      
    } catch (err: any) {
      console.error(`Failed to load ${activeTab} list:`, err);
      // 保持现有数据，不重置为错误
    } finally {
      setLoading(prev => ({ ...prev, list: false }));
    }
  }, [activeTab, filterType, sortType, sortDirection]);

  // 初始加载
  useEffect(() => {
    fetchDashboardData();
  }, [fetchDashboardData]);

  // 监听标签和筛选条件变化
  useEffect(() => {
    fetchListData();
  }, [fetchListData]);

  // 手动刷新
  const handleRefresh = () => {
    fetchDashboardData();
    fetchListData();
  };

  // 处理排序
  const handleSort = (type: 'time' | 'amount') => {
    if (sortType === type) {
      setSortDirection(prev => prev === 'asc' ? 'desc' : 'asc');
    } else {
      setSortType(type);
      setSortDirection('desc');
    }
  };

  // 处理交易操作
  const handleTradeAction = async (item: TradeItem, action: 'buy' | 'sell') => {
    try {
      // 检查余额
      if (action === 'sell' && assetBalance < item.amount) {
        alert(t.dashboard.actions.insufficientBalance || 'Insufficient balance');
        return;
      }
      
      // 确认交易
      const confirmMessage = action === 'buy' 
        ? t.dashboard.confirm.buy.replace('{amount}', item.amount.toString()).replace('{name}', item.name)
        : t.dashboard.confirm.sell.replace('{amount}', item.amount.toString()).replace('{name}', item.name);
      
      if (!window.confirm(confirmMessage)) {
        return;
      }
      
      // 执行交易API
      if (action === 'buy') {
        await tradeApi.createBuyOrder({
          itemId: item.id,
          amount: item.amount,
          paymentMethod: 'balance' // 默认使用余额支付
        });
        
        // 显示成功消息
        alert(t.dashboard.success.buy || 'Purchase successful!');
        
        // 刷新数据
        fetchDashboardData();
        
      } else {
        await tradeApi.createSellOrder({
          itemId: item.id,
          amount: item.amount,
          receiveMethod: 'balance'
        });
        
        alert(t.dashboard.success.sell || 'Sale successful!');
        fetchDashboardData();
      }
      
    } catch (err: any) {
      console.error('Trade error:', err);
      
      // 显示错误消息
      let errorMessage = t.dashboard.errors?.tradeFailed || 'Trade failed';
      if (err.response?.data?.message) {
        errorMessage = err.response.data.message;
      }
      
      alert(errorMessage);
    }
  };

  // 获取当前显示的列表
  const getActiveList = () => {
    switch (activeTab) {
      case 'platform': return platformList;
      case 'merchant': return merchantList;
      case 'member': return memberList;
      default: return [];
    }
  };

  const activeList = getActiveList();

  // 徽章文本
  const getBadgeText = (bonus: string | null) => {
    if (!bonus) return null;
    if (lang === 'zh-TW') return '⚡️限時回饋';
    if (lang === 'vi-VN') return '⚡️Khuyến mãi';
    return 'Flash Bonus';
  };

  // 加载状态显示
  if (loading.dashboard && loading.list && loading.assets) {
    return (
      <div className="flex flex-col h-full bg-slate-900 items-center justify-center">
        <LoadingSpinner size="lg" />
        <p className="text-slate-400 mt-4">{t.dashboard.loading || 'Loading dashboard...'}</p>
      </div>
    );
  }

  return (
    <div className="flex flex-col h-full bg-slate-900">
      {/* 顶部栏 */}
      <div className="px-5 pt-5 pb-2 shrink-0 z-10 bg-slate-900/95 backdrop-blur-sm">
        <div className="flex justify-between items-center">
          <div className="flex items-center gap-3 cursor-pointer" onClick={() => navigate('profile')}>
            <div className="w-10 h-10 rounded-full bg-gradient-to-tr from-emerald-500 to-slate-800 border border-emerald-400 p-[2px]">
              {userInfo?.avatar ? (
                <img src={userInfo.avatar} alt="avatar" className="rounded-full bg-slate-900 w-full h-full object-cover" />
              ) : (
                <img 
                  src={`https://api.dicebear.com/7.x/avataaars/svg?seed=${userInfo?.id || 'default'}`} 
                  alt="avatar" 
                  className="rounded-full bg-slate-900 w-full h-full" 
                />
              )}
            </div>
            <div>
              <h3 className="text-white font-bold text-sm">{userInfo?.nickname || 'Player_99'}</h3>
              <div className="flex items-center text-[10px] text-emerald-400 bg-emerald-900/30 px-2 rounded-full w-fit mt-1">
                <span className="w-1.5 h-1.5 rounded-full bg-emerald-500 mr-1 animate-pulse"></span>
                {userInfo?.verified ? t.common.verified : t.common.unverified}
              </div>
            </div>
          </div>
          
          <div className="flex items-center gap-2">
            {/* 刷新按钮 */}
            <button 
              onClick={handleRefresh}
              disabled={loading.dashboard || loading.list}
              className="p-2 bg-slate-800 rounded-full border border-slate-700 cursor-pointer hover:bg-slate-700 transition-colors disabled:opacity-50"
              title={t.dashboard.refresh || 'Refresh'}
            >
              <RefreshCw 
                size={20} 
                className={`text-slate-300 ${loading.dashboard || loading.list ? 'animate-spin' : ''}`} 
              />
            </button>
            
            {/* 通知按钮 */}
            <div 
              onClick={() => navigate('notifications')} 
              className="relative p-2 bg-slate-800 rounded-full border border-slate-700 cursor-pointer hover:bg-slate-700 transition-colors"
            >
              <Bell size={20} className="text-slate-300" />
              <span className="absolute top-1 right-1 w-2.5 h-2.5 bg-rose-500 rounded-full border border-slate-900"></span>
            </div>
          </div>
        </div>
        
        {/* 最后更新时间 */}
        {lastUpdated && (
          <div className="text-right text-[10px] text-slate-500 mt-2">
            {t.dashboard.lastUpdated || 'Last updated'}: {lastUpdated}
          </div>
        )}
      </div>

      {/* 错误提示 */}
      {error && (
        <div className="mx-5 mt-2 p-3 bg-rose-500/20 border border-rose-500/50 rounded-lg">
          <div className="flex items-center gap-2 text-rose-400">
            <AlertCircle size={16} />
            <span className="text-sm">{error}</span>
            <button 
              onClick={() => setError(null)}
              className="ml-auto text-xs text-slate-400 hover:text-white"
            >
              {t.common.dismiss}
            </button>
          </div>
        </div>
      )}

      <div className="flex-1 overflow-y-auto px-5 pb-5 scroll-smooth no-scrollbar">
        {/* 统计卡片 */}
        <div className="grid grid-cols-3 gap-3 mb-6 mt-2">
          <div className="bg-slate-800 rounded-xl p-3 border border-slate-700 shadow-lg relative overflow-hidden group">
            <p className="text-slate-400 text-[10px] font-bold mb-1">{t.dashboard.avail}</p>
            <h3 className="text-lg font-mono font-bold text-blue-400 mb-2 tracking-tight">
              {loading.assets ? (
                <div className="h-6 w-20 bg-slate-700 rounded animate-pulse">{assetBalance.toLocaleString()}</div>
              ) : (
                assetBalance.toLocaleString()
              )}
            </h3>
            <div className="flex items-center text-[10px] text-slate-500">
              <Coins size={10} className="mr-1 text-yellow-500" />
              {t.common.points}
            </div>
          </div>
          
          <div className="bg-slate-800 rounded-xl p-3 border border-slate-700 shadow-lg relative overflow-hidden group">
            <p className="text-slate-400 text-[10px] font-bold mb-1">{t.dashboard.todayBuy}</p>
            <h3 className="text-lg font-mono font-bold text-emerald-500 mb-2 tracking-tight">
              {loading.dashboard ? (
                <div className="h-6 w-20 bg-slate-700 rounded animate-pulse"></div>
              ) : (
                `+${todayStats.buy.toLocaleString()}`
              )}
            </h3>
            <div className="flex items-center text-[10px] text-emerald-500/80">
              <TrendingUp size={10} className="mr-1" />
              {todayStats.buyRate}
            </div>
          </div>
          
          <div className="bg-slate-800 rounded-xl p-3 border border-slate-700 shadow-lg relative overflow-hidden group">
            <p className="text-slate-400 text-[10px] font-bold mb-1">{t.dashboard.todaySell}</p>
            <h3 className="text-lg font-mono font-bold text-rose-500 mb-2 tracking-tight">
              {loading.dashboard ? (
                <div className="h-6 w-20 bg-slate-700 rounded animate-pulse"></div>
              ) : (
                `-${todayStats.sell.toLocaleString()}`
              )}
            </h3>
            <div className="flex items-center text-[10px] text-rose-400/80">
              <TrendingDown size={10} className="mr-1" />
              {todayStats.sellStatus}
            </div>
          </div>
        </div>

        {/* 标签页 */}
        <div className="mb-4">
          <div className="flex p-1 bg-slate-800 rounded-lg">
            {(['platform', 'merchant', 'member'] as const).map(tab => (
              <button 
                key={tab} 
                onClick={() => { setActiveTab(tab); setFilterType('all'); }} 
                disabled={loading.list}
                className={`flex-1 py-2 text-xs font-bold rounded-md transition-all ${activeTab === tab ? 'bg-slate-700 text-white shadow-sm' : 'text-slate-500 hover:text-slate-300'} disabled:opacity-50`}
              >
                {t.dashboard.tabs[tab]}
              </button>
            ))}
          </div>
        </div>

        {/* 筛选和排序 */}
        <div className="flex items-center justify-between mb-4">
          <div className="flex gap-3 text-xs font-bold">
            {(['all', 'buy', 'sell'] as const).map(type => (
              <button 
                key={type} 
                onClick={() => setFilterType(type)} 
                disabled={loading.list}
                className={`pb-1 border-b-2 transition-colors ${filterType === type ? 'text-emerald-400 border-emerald-400' : 'text-slate-500 border-transparent hover:text-slate-300'} disabled:opacity-50`}
              >
                {type === 'all' ? t.common.all : (type === 'buy' ? t.dashboard.filter.buy : t.dashboard.filter.sell)}
              </button>
            ))}
          </div>
          
          <div className="flex bg-slate-800 rounded-md p-0.5">
            <button 
              onClick={() => handleSort('amount')} 
              disabled={loading.list}
              className={`p-1.5 rounded flex items-center gap-1 ${sortType === 'amount' ? 'bg-slate-700 text-white' : 'text-slate-500'} disabled:opacity-50`}
            >
              <ArrowUpDown size={14} />
              {sortType === 'amount' && <span className="text-[10px] font-mono">{sortDirection === 'asc' ? '↑' : '↓'}</span>}
            </button>
            <button 
              onClick={() => handleSort('time')} 
              disabled={loading.list}
              className={`p-1.5 rounded flex items-center gap-1 ${sortType === 'time' ? 'bg-slate-700 text-white' : 'text-slate-500'} disabled:opacity-50`}
            >
              <Clock size={14} />
              {sortType === 'time' && <span className="text-[10px] font-mono">{sortDirection === 'asc' ? '↑' : '↓'}</span>}
            </button>
          </div>
        </div>

        {/* 列表内容 */}
        <div className="space-y-3 min-h-[300px]">
          {loading.list ? (
            // 加载状态
            <div className="flex flex-col items-center justify-center py-12">
              <LoadingSpinner />
              <p className="text-slate-400 mt-2 text-sm">{t.dashboard.loadingList || 'Loading list...'}</p>
            </div>
          ) : activeList.length === 0 ? (
            // 空状态
            <div className="flex flex-col items-center justify-center py-12">
              <div className="w-16 h-16 bg-slate-800 rounded-full flex items-center justify-center mb-4">
                <ShoppingBag size={24} className="text-slate-500" />
              </div>
              <p className="text-slate-400 text-sm">{t.dashboard.emptyList || 'No items found'}</p>
              <button 
                onClick={handleRefresh}
                className="mt-4 text-emerald-400 text-sm hover:underline"
              >
                {t.dashboard.refreshList || 'Refresh list'}
              </button>
            </div>
          ) : (
            // 正常列表
            activeList.map((item) => {
              const canAfford = item.type === 'buy' ? assetBalance >= item.amount : true;
              
              return (
                <Card key={item.id} className="flex justify-between items-center p-3 relative overflow-hidden group">
                  <div className={`absolute left-0 top-0 bottom-0 w-1 ${item.type === 'sell' ? 'bg-emerald-500' : 'bg-rose-500'}`}></div>
                  <div className="flex flex-col gap-1 pl-2">
                    <div className="flex items-center gap-2">
                      <span className="text-white font-bold text-sm">{item.name}</span>
                      <div className="flex text-yellow-500 text-[10px]">★ {item.rating}</div>
                      <span className="text-[10px] text-slate-500 font-mono ml-1">{item.time}</span>
                    </div>
                    <div className="flex items-center">
                      <span className="text-xl font-mono font-bold text-white tracking-tighter">{item.amount.toLocaleString()}</span>
                      <span className="text-xs text-slate-500 ml-1 mt-2">P</span>
                    </div>
                    {item.bonus && (
                      <div className="flex mt-1">
                        <Badge type="red" text={getBadgeText(item.bonus) || ''} />
                      </div>
                    )}
                  </div>
                  
                  <div className="flex flex-col items-end gap-2">
                    {item.type === 'sell' ? (
                      <NeonButton 
                        variant="primary" 
                        className="w-20 h-9 text-xs" 
                        onClick={() => handleTradeAction(item, 'buy')}
                        disabled={loading.dashboard}
                      >
                        {loading.dashboard ? (
                          <div className="w-4 h-4 border-2 border-white border-t-transparent rounded-full animate-spin"></div>
                        ) : (
                          t.dashboard.actions.buy
                        )}
                      </NeonButton>
                    ) : (
                      <>
                        <NeonButton 
                          variant="danger" 
                          className="w-20 h-9 text-xs" 
                          onClick={() => handleTradeAction(item, 'sell')}
                          disabled={!canAfford || loading.dashboard}
                        >
                          {loading.dashboard ? (
                            <div className="w-4 h-4 border-2 border-white border-t-transparent rounded-full animate-spin"></div>
                          ) : (
                            t.dashboard.actions.sell
                          )}
                        </NeonButton>
                        {!canAfford && (
                          <span className="text-[10px] text-rose-500">
                            {t.dashboard.actions.need} {item.amount.toLocaleString()}
                          </span>
                        )}
                      </>
                    )}
                  </div>
                </Card>
              );
            })
          )}
        </div>

        {/* 快速操作 */}
        <div className="mt-8 mb-6 pt-6 border-t border-slate-800">
          <p className="text-white text-xs font-bold mb-3 flex items-center">
            <span className="w-1 h-3 bg-emerald-500 mr-2 rounded-full"></span>
            {t.dashboard.quickActions}
          </p>
          
          <div className="grid grid-cols-4 gap-2">
            {quickActions.length > 0 ? (
              quickActions.map(action => (
                <button 
                  key={action.id}
                  onClick={() => {}}
                  disabled={!action.enabled}
                  className={`flex flex-col items-center justify-center p-3 rounded-lg transition-colors border shadow-lg ${
                    action.enabled 
                      ? 'bg-slate-800 border-slate-700 hover:bg-slate-700' 
                      : 'bg-slate-900 border-slate-800 opacity-50 cursor-not-allowed'
                  }`}
                >
                  {/* 这里可以根据action.icon动态渲染图标 */}
                  <ShoppingBag size={20} className="text-emerald-400 mb-1" />
                  <span className="text-[10px] text-slate-300">{action.title}</span>
                  {action.badge && (
                    <span className="absolute top-1 right-1 w-4 h-4 bg-rose-500 text-[8px] text-white rounded-full flex items-center justify-center">
                      {action.badge}
                    </span>
                  )}
                </button>
              ))
            ) : (
              // 默认快速操作
              <>
                <button onClick={() => navigate('points-mall')} className="flex flex-col items-center justify-center p-3 bg-slate-800 rounded-lg hover:bg-slate-700 transition-colors border border-slate-700 shadow-lg">
                  <ShoppingBag size={20} className="text-emerald-400 mb-1" />
                  <span className="text-[10px] text-slate-300">{t.dashboard.qa.mall}</span>
                </button>
                <button onClick={() => navigate('my-wallet')} className="flex flex-col items-center justify-center p-3 bg-slate-800 rounded-lg hover:bg-slate-700 transition-colors border border-slate-700 shadow-lg">
                  <Wallet size={20} className="text-yellow-400 mb-1" />
                  <span className="text-[10px] text-slate-300">{t.dashboard.qa.wallet}</span>
                </button>
                <button onClick={() => navigate('profile')} className="flex flex-col items-center justify-center p-3 bg-slate-800 rounded-lg hover:bg-slate-700 transition-colors border border-slate-700 shadow-lg">
                  <Settings size={20} className="text-blue-400 mb-1" />
                  <span className="text-[10px] text-slate-300">{t.dashboard.qa.settings}</span>
                </button>
                <button onClick={() => navigate('system-announcements')} className="flex flex-col items-center justify-center p-3 bg-slate-800 rounded-lg hover:bg-slate-700 transition-colors border border-slate-700 shadow-lg">
                  <Megaphone size={20} className="text-rose-400 mb-1" />
                  <span className="text-[10px] text-slate-300">{t.dashboard.qa.announce}</span>
                </button>
              </>
            )}
          </div>
        </div>
      </div>
    </div>
  );
};

export default DashboardView;

// src/views/DashboardView.vue
<template>
  <div class="flex flex-col h-full bg-slate-900">
    <!-- Header -->
    <div class="px-5 pt-5 pb-2 shrink-0 z-10 bg-slate-900/95 backdrop-blur-sm">
      <div class="flex justify-between items-center">
        <div class="flex items-center gap-3 cursor-pointer" @click="$router.push('/profile')">
          <div class="w-10 h-10 rounded-full bg-gradient-to-tr from-emerald-500 to-slate-800 border border-emerald-400 p-[2px]">
            <img 
              v-if="userInfo.avatar"
              :src="userInfo.avatar" 
              alt="avatar" 
              class="rounded-full bg-slate-900 w-full h-full object-cover" 
            />
            <img 
              v-else
              :src="defaultAvatar" 
              alt="avatar" 
              class="rounded-full bg-slate-900 w-full h-full" 
            />
          </div>
          <div>
            <h3 class="text-white font-bold text-sm">{{ displayName }}</h3>
            <div class="flex items-center text-[10px] text-emerald-400 bg-emerald-900/30 px-2 rounded-full w-fit mt-1">
              <span class="w-1.5 h-1.5 rounded-full bg-emerald-500 mr-1 animate-pulse"></span>
              {{ userInfo.verified ? 'verified' : t.common.unverified }}
            </div>
          </div>
        </div>
        <div @click="$router.push('/notifications')" class="relative p-2 bg-slate-800 rounded-full border border-slate-700 cursor-pointer hover:bg-slate-700 transition-colors">
          <Bell :size="20" class="text-slate-300" />
          <span v-if="unreadNotifications > 0" class="absolute top-1 right-1 w-2.5 h-2.5 bg-rose-500 rounded-full border border-slate-900"></span>
        </div>
      </div>
    </div>

    <!-- Main Content -->
    <div class="flex-1 overflow-y-auto px-5 pb-5 scroll-smooth no-scrollbar">
      <!-- Loading State -->
      <div v-if="loading" class="flex flex-col items-center justify-center py-12">
        <div class="animate-spin rounded-full h-12 w-12 border-b-2 border-emerald-500 mb-4"></div>
        <p class="text-slate-400 text-sm">{{ t.common.loading }}</p>
      </div>

      <!-- Error State -->
      <div v-else-if="error" class="py-8 text-center">
        <div class="text-rose-500 mb-3">{{ error }}</div>
        <NeonButton variant="outline" @click="fetchDashboardData">
          <RefreshCw :size="14" class="mr-2" />
          {{ t.common.retry }}
        </NeonButton>
      </div>

      <!-- Content -->
      <template v-else>
        <!-- Balance Cards -->
        <div class="grid grid-cols-3 gap-3 mb-6 mt-2">
          <div class="bg-slate-800 rounded-xl p-3 border border-slate-700 shadow-lg relative overflow-hidden group">
            <p class="text-slate-400 text-[10px] font-bold mb-1">{{ t.dashboard.avail }}</p>
            <h3 class="text-lg font-mono font-bold text-blue-400 mb-2 tracking-tight">
              {{ dashboardData.wallet?.balance.toLocaleString() || '0' }}
            </h3>
            <div class="flex items-center text-[10px] text-slate-500">
              <Coins :size="10" class="mr-1 text-yellow-500" />
              {{ t.common.points }}
            </div>
          </div>
          <div class="bg-slate-800 rounded-xl p-3 border border-slate-700 shadow-lg relative overflow-hidden group">
            <p class="text-slate-400 text-[10px] font-bold mb-1">{{ t.dashboard.todayBuy }}</p>
            <h3 class="text-lg font-mono font-bold text-emerald-500 mb-2 tracking-tight">
              +{{ dashboardData.todayStats?.buy?.toLocaleString() || '0' }}
            </h3>
            <div class="flex items-center text-[10px] text-emerald-500/80">
              <TrendingUp :size="10" class="mr-1" />
              {{ dashboardData.todayStats?.buyRate || '0%' }}
            </div>
          </div>
          <div class="bg-slate-800 rounded-xl p-3 border border-slate-700 shadow-lg relative overflow-hidden group">
            <p class="text-slate-400 text-[10px] font-bold mb-1">{{ t.dashboard.todaySell }}</p>
            <h3 class="text-lg font-mono font-bold text-rose-500 mb-2 tracking-tight">
              -{{ dashboardData.todayStats?.sell?.toLocaleString() || '0' }}
            </h3>
            <div class="flex items-center text-[10px] text-rose-400/80">
              <TrendingDown :size="10" class="mr-1" />
              {{ dashboardData.todayStats?.sellRate || '0' }}
            </div>
          </div>
        </div>

        <!-- Tabs: Platform / Merchant / Member -->
        <div class="mb-4">
          <div class="flex p-1 bg-slate-800 rounded-lg">
            <button 
              v-for="tab in ['platform', 'merchant', 'member']" 
              :key="tab"
              @click="handleTabChange(tab)"
              :class="`flex-1 py-2 text-xs font-bold rounded-md transition-all ${activeTab === tab ? 'bg-slate-700 text-white shadow-sm' : 'text-slate-500 hover:text-slate-300'}`"
            >
              {{ t.dashboard.tabs[tab] }}
            </button>
          </div>
        </div>

        <!-- Filter & Sort -->
        <div class="flex items-center justify-between mb-4">
          <div class="flex gap-3 text-xs font-bold">
            <button 
              v-for="type in ['all', 'buy', 'sell']" 
              :key="type"
              @click="filterType = type"
              :class="`pb-1 border-b-2 transition-colors ${filterType === type ? 'text-emerald-400 border-emerald-400' : 'text-slate-500 border-transparent hover:text-slate-300'}`"
            >
              {{ type === 'all' ? t.common.all : (type === 'buy' ? t.dashboard.filter.buy : t.dashboard.filter.sell) }}
            </button>
          </div>
          <div class="flex bg-slate-800 rounded-md p-0.5">
            <button 
              @click="handleSort('amount')" 
              :class="`p-1.5 rounded flex items-center gap-1 ${sortType === 'amount' ? 'bg-slate-700 text-white' : 'text-slate-500'}`" 
              :title="t.dashboard.sort.amount"
            >
              <ArrowUpDown :size="14" />
              <span v-if="sortType === 'amount'" class="text-[10px] font-mono">{{ sortDirection === 'asc' ? '↑' : '↓' }}</span>
            </button>
            <button 
              @click="handleSort('time')" 
              :class="`p-1.5 rounded flex items-center gap-1 ${sortType === 'time' ? 'bg-slate-700 text-white' : 'text-slate-500'}`" 
              :title="t.dashboard.sort.time"
            >
              <Clock :size="14" />
              <span v-if="sortType === 'time'" class="text-[10px] font-mono">{{ sortDirection === 'asc' ? '↑' : '↓' }}</span>
            </button>
          </div>
        </div>

        <!-- Trading List -->
        <div class="space-y-3 min-h-[300px]">
          <!-- Loading for trading list -->
          <div v-if="tradingLoading" class="space-y-3">
            <div v-for="i in 3" :key="i" class="bg-slate-800 rounded-lg p-3 animate-pulse">
              <div class="flex justify-between items-center">
                <div class="space-y-2">
                  <div class="h-4 bg-slate-700 rounded w-24"></div>
                  <div class="h-6 bg-slate-700 rounded w-16"></div>
                </div>
                <div class="h-9 w-20 bg-slate-700 rounded"></div>
              </div>
            </div>
          </div>

          <!-- Empty State -->
          <div v-else-if="processedList.length === 0" class="text-center py-12">
            <div class="text-slate-500 mb-2">{{ t.dashboard.noData }}</div>
            <NeonButton variant="outline" size="sm" @click="fetchTradingList">
              <RefreshCw :size="12" class="mr-1" />
              {{ t.common.refresh }}
            </NeonButton>
          </div>

          <!-- Trading Items -->
          <Card 
            v-for="item in processedList" 
            :key="item.id" 
            class="flex justify-between items-center p-3 relative overflow-hidden group"
          >
            <div :class="`absolute left-0 top-0 bottom-0 w-1 ${item.type === 'sell' ? 'bg-emerald-500' : 'bg-rose-500'}`"></div>
            <div class="flex flex-col gap-1 pl-2">
              <div class="flex items-center gap-2">
                <span class="text-white font-bold text-sm">{{ item.name }}</span>
                <div class="flex text-yellow-500 text-[10px]">★ {{ item.rating }}</div>
                <span class="text-[10px] text-slate-500 font-mono ml-1">{{ item.time }}</span>
              </div>
              <div class="flex items-center">
                <span class="text-xl font-mono font-bold text-white tracking-tighter">{{ item.amount_points?.toLocaleString() }}</span>
                <span class="text-xs text-slate-500 ml-1 mt-2">P</span>
              </div>
              <div v-if="item.bonus" class="flex mt-1">
                <span class="text-[10px] px-2 py-0.5 rounded border bg-rose-900/50 text-rose-400 border-rose-500/30 ml-2 animate-pulse">
                  ⚡️{{ getBadgeText(item.bonus) }}
                </span>
              </div>
            </div>
            <div class="flex flex-col items-end gap-2">
              <NeonButton 
                v-if="item.type === 'sell'"
                variant="primary" 
                class="w-20 h-9 text-xs" 
                @click="handleBuy(item)"
                :loading="buyLoading && selectedItemId === item.id"
              >
                {{ t.dashboard.actions.buy }}
              </NeonButton>
              <template v-else>
                <NeonButton 
                  variant="danger" 
                  class="w-20 h-9 text-xs" 
                  @click="handleSell(item)"
                  :disabled="!canAfford(item)"
                  :loading="sellLoading && selectedItemId === item.id"
                >
                  {{ t.dashboard.actions.sell }}
                </NeonButton>
                <span v-if="!canAfford(item)" class="text-[10px] text-rose-500">
                  {{ t.dashboard.actions.need }} {{ item.amount.toLocaleString() }}
                </span>
              </template>
            </div>
          </Card>
        </div>

        <!-- Quick Actions -->
        <div class="mt-8 mb-6 pt-6 border-t border-slate-800">
          <p class="text-white text-xs font-bold mb-3 flex items-center">
            <span class="w-1 h-3 bg-emerald-500 mr-2 rounded-full"></span>
            {{ t.dashboard.quickActions }}
          </p>
          <div class="grid grid-cols-4 gap-2">
            <button @click="$router.push('/points-mall')" class="flex flex-col items-center justify-center p-3 bg-slate-800 rounded-lg hover:bg-slate-700 transition-colors border border-slate-700 shadow-lg">
              <ShoppingBag :size="20" class="text-emerald-400 mb-1" />
              <span class="text-[10px] text-slate-300">{{ t.dashboard.qa.mall }}</span>
            </button>
            <button @click="$router.push('/my-wallet')" class="flex flex-col items-center justify-center p-3 bg-slate-800 rounded-lg hover:bg-slate-700 transition-colors border border-slate-700 shadow-lg">
              <Wallet :size="20" class="text-yellow-400 mb-1" />
              <span class="text-[10px] text-slate-300">{{ t.dashboard.qa.wallet }}</span>
            </button>
            <button @click="$router.push('/profile')" class="flex flex-col items-center justify-center p-3 bg-slate-800 rounded-lg hover:bg-slate-700 transition-colors border border-slate-700 shadow-lg">
              <Settings :size="20" class="text-blue-400 mb-1" />
              <span class="text-[10px] text-slate-300">{{ t.dashboard.qa.settings }}</span>
            </button>
            <button @click="$router.push('/system-announcements')" class="flex flex-col items-center justify-center p-3 bg-slate-800 rounded-lg hover:bg-slate-700 transition-colors border border-slate-700 shadow-lg">
              <Megaphone :size="20" class="text-rose-400 mb-1" />
              <span class="text-[10px] text-slate-300">{{ t.dashboard.qa.announce }}</span>
            </button>
          </div>
        </div>
      </template>
    </div>
  </div>
</template>

<script setup>
import { ref, computed, onMounted, watch } from 'vue'
import { useRouter } from 'vue-router'
import { 
  Bell, 
  Coins, 
  TrendingUp, 
  TrendingDown, 
  ShoppingBag, 
  Wallet, 
  Settings, 
  Megaphone, 
  ArrowUpDown, 
  Clock,
  RefreshCw
} from 'lucide-vue-next'
import Card from '@/components/Card.vue'
import NeonButton from '@/components/NeonButton.vue'
import { useTranslation } from '@/composables/useTranslation'
import { useAuthStore } from '@/stores/auth'
import { api, post } from '@/utils/api'
import { showToast } from '@/utils/notification'

const router = useRouter()
const authStore = useAuthStore()
const { t } = useTranslation()

// State
const activeTab = ref('merchant')
const filterType = ref('all')
const sortType = ref('time')
const sortDirection = ref('desc')
const loading = ref(false)
const error = ref('')
const dashboardData = ref({})
const tradingList = ref([])
const tradingLoading = ref(false)
const buyLoading = ref(false)
const sellLoading = ref(false)
const selectedItemId = ref(null)
const unreadNotifications = ref(0)

// Computed
const userInfo = computed(() => {
  return authStore.user || {}
})

const displayName = computed(() => {
  return userInfo.value.nickname || 
         userInfo.value.username || 
         userInfo.value.name || 
         t.profile.defaultName
})

const defaultAvatar = computed(() => {
  const seed = userInfo.value.username || 
              userInfo.value.nickname || 
              userInfo.value.userId || 
              'User'
  return `https://api.dicebear.com/7.x/avataaars/svg?seed=${encodeURIComponent(seed)}`
})

const processedList = computed(() => {
  let list = tradingList.value

  // Filter by type
  if (filterType.value === 'buy') {
    list = list.filter(item => item.type === 'sell')
  } else if (filterType.value === 'sell') {
    list = list.filter(item => item.type === 'buy')
  }

  // Sort
  list.sort((a, b) => {
    let diff = 0
    if (sortType.value === 'amount') {
      diff = a.amount - b.amount
    } else {
      diff = a.time.localeCompare(b.time)
    }
    return sortDirection.value === 'asc' ? diff : -diff
  })

  return list
})

// Methods
function canAfford(item) {
  return item.type === 'buy' ? dashboardData.value.wallet.balance >= item.amount : true
}

function getBadgeText(bonus) {
  if (!bonus) return null
  if (bonus === 'flash') return t.dashboard.badges.flash
  if (bonus === 'bonus') return t.dashboard.badges.bonus
  if (bonus === 'fast') return t.dashboard.badges.fast
  if (bonus === 'official') return t.dashboard.badges.official
  if (bonus === 'fee-free') return t.dashboard.badges.feeFree
  if (bonus === 'urgent') return t.dashboard.badges.urgent
  if (bonus === 'fast-pay') return t.dashboard.badges.fastPay
  return bonus
}

async function fetchDashboardData() {
  if (!authStore.isAuthenticated) {
    router.push('/login')
    return
  }

  loading.value = true
  error.value = ''

  try {
    const response = await api.get('/wallet')
    
    if (response.data.success) {
      dashboardData.value = response.data.data
      unreadNotifications.value = response.data.data.unreadNotifications || 0
    } else {
      error.value = response.data.message || t.common.requestFailed
    }
  } catch (err) {
    console.error('Dashboard data fetch error:', err)
    error.value = err.response?.data?.message || err.message || t.common.networkError
    
    // 如果 token 失效，清除登录状态
    if (err.response?.status === 401) {
      authStore.logout()
      router.push('/login')
    }
  } finally {
    loading.value = false
  }
}

async function fetchTradingList() {
  tradingLoading.value = true

  try {
    const response = await api.get('/trading/list', {
      params: {
        type: activeTab.value
      }
    })
    
    if (response.data.success) {
      tradingList.value = response.data.data
    } else {
      showToast({
        type: 'error',
        title: t.dashboard.fetchFailed,
        message: response.data.message || t.common.requestFailed
      })
    }
  } catch (err) {
    console.error('Trading list fetch error:', err)
    showToast({
      type: 'error',
      title: t.dashboard.fetchFailed,
      message: err.message || t.common.networkError
    })
  } finally {
    tradingLoading.value = false
  }
}

async function handleBuy(item) {
  if (buyLoading.value) return
  
  selectedItemId.value = item.id
  buyLoading.value = true

  try {
    const response = await post('/trading/buy', {
      itemId: item.id,
      amount: item.amount_points
    })
    
    if (response.data.success) {
      /*showToast({
        type: 'success',
        title: response.data.message,
        message: response.data.message
      })*/
      
      // 刷新数据
      fetchDashboardData()
      fetchTradingList()
      
      // 跳转到交易页面
      router.push({
        name: 'trade-buy',
        params: { item: JSON.stringify(item) }
      })
    } else {
      showToast({
        type: 'error',
        title: t.dashboard.buyFailed,
        message: response.data.message || t.common.requestFailed
      })
    }
  } catch (err) {
    console.error('Buy error:', err)
    showToast({
      type: 'error',
      title: 'error',
      message:  err?.response?.data?.message
    })
  } finally {
    buyLoading.value = false
    selectedItemId.value = null
    router.push({
        name: 'trade-buy',
        params: { item: JSON.stringify(item) }
      })
  }
}

async function handleSell(item) {
  if (sellLoading.value || !canAfford(item)) return
  
  selectedItemId.value = item.id
  sellLoading.value = true

  try {
    const response = await post('/trading/sell', {
      itemId: item.id,
      amount: item.amount_points
    })
    
    if (response.data.success) {
      showToast({
        type: 'success',
        title: t.value.dashboard.sellSuccess,
        message: t.value.dashboard.sellSuccessMessage
      })
      
      // 刷新数据
      //fetchDashboardData()
      //fetchTradingList()
      
      // 跳转到交易页面
      router.push({
        name: 'trade-sell',
        params: { item: JSON.stringify(item) }
      })
    } else {
      showToast({
        type: 'error',
        title: t.value.dashboard.sellFailed,
        message: response.data.message || t.common.requestFailed
      })
    }
  } catch (err) {
    console.error('Sell error:', err)
    showToast({
      type: 'error',
      title: t.value.dashboard.sellFailed,
      message: err.message || t.common.networkError
    })
  } finally {
    sellLoading.value = false
    selectedItemId.value = null
  }
}

function handleTabChange(tab) {
  activeTab.value = tab
  filterType.value = 'all'
  fetchTradingList()
}

function handleSort(type) {
  if (sortType.value === type) {
    sortDirection.value = sortDirection.value === 'asc' ? 'desc' : 'asc'
  } else {
    sortType.value = type
    sortDirection.value = 'desc'
  }
}

// Lifecycle
onMounted(() => {
  if (!authStore.isAuthenticated) {
    router.push('/login')
    return
  }
  
  fetchDashboardData()
  fetchTradingList()
})

// Watch for tab changes
watch(activeTab, () => {
  fetchTradingList()
})
</script>

<style scoped>
.no-scrollbar::-webkit-scrollbar {
  display: none;
}

.no-scrollbar {
  -ms-overflow-style: none;
  scrollbar-width: none;
}
</style>
