// src/views/LoginView.tsx
import React, { useState } from 'react';
import { Shield, Loader2 } from 'lucide-react';
import { ViewProps } from '../types';
import { InputField, NeonButton, LanguageSwitcher } from '../components';
import { User, Lock, Key } from 'lucide-react';
import { authApi } from '../services/api';

const LoginView: React.FC<ViewProps> = ({ navigate, t, lang, setLang }) => {
  const [account, setAccount] = useState('');
  const [password, setPassword] = useState('');
  const [captcha, setCaptcha] = useState('');
  const [captchaImage, setCaptchaImage] = useState('');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');

  // 获取验证码图片
  const fetchCaptcha = async () => {
    try {
      // 这里假设API返回base64格式的图片
      const response = await authApi.getCaptcha();
      if (response.data?.captchaImage) {
        setCaptchaImage(response.data?.captchaImage);
      }
    } catch (err) {
      console.error('获取验证码失败:', err);
      // 模拟一个验证码（实际开发中应从API获取）
      setCaptchaImage('data:image/svg+xml;base64,' + btoa(`
        <svg width="120" height="40" xmlns="http://www.w3.org/2000/svg">
          <rect width="120" height="40" fill="#1e293b"/>
          <text x="10" y="25" font-family="Arial" font-size="16" fill="#10b981">${Math.random().toString(36).substr(2, 6).toUpperCase()}</text>
          <line x1="0" y1="10" x2="120" y2="30" stroke="#475569" stroke-width="1"/>
          <line x1="0" y1="30" x2="120" y2="10" stroke="#475569" stroke-width="1"/>
        </svg>
      `));
    }
  };

  // 组件加载时获取验证码
  React.useEffect(() => {
    fetchCaptcha();
  }, []);

  // 刷新验证码
  const refreshCaptcha = () => {
    fetchCaptcha();
  };

  // 处理登录
  const handleLogin = async () => {
    // 验证输入
    if (!account.trim()) {
      setError(t.login.errors?.accountRequired || '请输入账号');
      return;
    }
    if (!password.trim()) {
      setError(t.login.errors?.passwordRequired || '请输入密码');
      return;
    }
    if (!captcha.trim()) {
      setError(t.login.errors?.captchaRequired || '请输入验证码');
      return;
    }

    setLoading(true);
    setError('');

    try {
      // 调用登录API
      const response = await authApi.login({
        account: account.trim(),
        password: password.trim(),
        captcha: captcha.trim(),
      });

      // 处理登录成功
      if (response.data?.token) {
        // 存储token
        localStorage.setItem('token', response.data.token);
        
        // 存储用户信息
        if (response.data.user) {
          localStorage.setItem('user', JSON.stringify(response.data.user));
        }
        
        // 登录成功，跳转到仪表板
        navigate('dashboard');
        
        // 显示成功消息（如果有的话）
        if (response.data.message) {
          // 可以使用toast或消息提示组件
          console.log('登录成功:', response.data.message);
        }
      } else {
        setError(t.login.errors?.invalidCredentials || '登录失败，请检查账号密码');
      }
    } catch (err: any) {
      // 处理错误
      console.error('登录错误:', err);
      
      // 根据错误类型显示不同的错误消息
      if (err.response?.status === 401) {
        setError(t.login.errors?.invalidCredentials || '账号或密码错误');
      } else if (err.response?.status === 403) {
        setError(t.login.errors?.invalidCaptcha || '验证码错误');
      } else if (err.response?.status === 429) {
        setError(t.login.errors?.tooManyAttempts || '尝试次数过多，请稍后再试');
      } else if (err.message === 'Network Error') {
        setError(t.login.errors?.networkError || '网络错误，请检查网络连接');
      } else {
        setError(t.login.errors?.unknownError || `登录失败: ${err.message || '未知错误'}`);
      }
      
      // 登录失败时刷新验证码
      refreshCaptcha();
    } finally {
      setLoading(false);
      setCaptcha(''); // 清空验证码输入
    }
  };

  // 处理回车键登录
  const handleKeyPress = (e: React.KeyboardEvent) => {
    if (e.key === 'Enter' && !loading) {
      handleLogin();
    }
  };

  return (
    <div className="flex flex-col h-full justify-center px-6 relative overflow-hidden">
      <div className="absolute top-[-10%] left-[-10%] w-60 h-60 bg-emerald-500/10 rounded-full blur-3xl"></div>
      <div className="absolute bottom-[-10%] right-[-10%] w-60 h-60 bg-rose-500/10 rounded-full blur-3xl"></div>
      <div className="absolute top-6 right-6 z-20">
        <LanguageSwitcher currentLang={lang} setLang={setLang} />
      </div>
      <div className="z-10 w-full max-w-sm mx-auto">
        <div className="text-center mb-10">
          <div className="inline-flex items-center justify-center w-20 h-20 rounded-full bg-slate-800 border-2 border-emerald-500 shadow-[0_0_20px_rgba(16,185,129,0.3)] mb-4">
            <Shield size={40} className="text-emerald-400" />
          </div>
          <h1 className="text-3xl font-bold text-white tracking-widest">{t.appName}</h1>
          <p className="text-slate-400 text-sm mt-2">{t.appSub}</p>
        </div>
        
        {/* 错误提示 */}
        {error && (
          <div className="mb-4 p-3 bg-rose-500/20 border border-rose-500/50 rounded-lg text-rose-300 text-sm">
            {error}
          </div>
        )}
        
        <div className="space-y-4" onKeyPress={handleKeyPress}>
          <InputField 
            icon={User} 
            placeholder={t.login.accPlaceholder} 
            value={account}
            onChange={(e) => setAccount(e.target.value)}
            disabled={loading}
          />
          
          <InputField 
            icon={Lock} 
            isSecure={true} 
            placeholder={t.login.passPlaceholder} 
            value={password}
            onChange={(e) => setPassword(e.target.value)}
            disabled={loading}
          />
          
          {/* 验证码输入区域 */}
          <div className="space-y-2">
            <div className="flex items-center gap-2">
              <InputField 
                icon={Key}
                isSecure={false}
                placeholder={t.login.captchaPlaceholder}
                value={captcha}
                onChange={(e) => setCaptcha(e.target.value)}
                disabled={loading}
                className="flex-1"
              />
              
              {/* 验证码图片 */}
              <div 
                className="h-12 w-32 rounded-lg border border-slate-700 bg-slate-800 overflow-hidden cursor-pointer hover:border-emerald-500/50 transition-colors"
                onClick={refreshCaptcha}
                title={t.login.refreshCaptcha || "点击刷新验证码"}
              >
                {captchaImage ? (
                  <img 
                    src={captchaImage} 
                    alt="验证码" 
                    className="w-full h-full object-cover"
                  />
                ) : (
                  <div className="w-full h-full flex items-center justify-center">
                    <Loader2 size={20} className="text-slate-500 animate-spin" />
                  </div>
                )}
              </div>
            </div>
            
            {/* 刷新验证码提示 */}
            <p className="text-xs text-slate-500 text-right">
              {t.login.captchaHint || "看不清？点击图片刷新"}
            </p>
          </div>
          
          {/* 登录按钮 */}
          <NeonButton 
            fullWidth 
            onClick={handleLogin}
            disabled={loading}
          >
            {loading ? (
              <span className="flex items-center justify-center">
                <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                {t.login.loggingIn || "登录中..."}
              </span>
            ) : (
              t.login.loginBtn
            )}
          </NeonButton>
          
          <div className="flex justify-between text-xs text-slate-400 mt-4">
            <button 
              onClick={() => navigate('register')} 
              className="hover:text-emerald-400 underline decoration-slate-600 disabled:opacity-50"
              disabled={loading}
            >
              {t.login.register}
            </button>
            <button 
              onClick={() => navigate('forgot-password')} 
              className="hover:text-emerald-400 hover:underline decoration-slate-600 transition-all disabled:opacity-50"
              disabled={loading}
            >
              {t.login.forgotPass}
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};

export default LoginView;

// src/views/LoginView.vue
<template>
  <div class="flex flex-col h-full justify-center px-6 relative overflow-hidden">
    <div class="absolute top-[-10%] left-[-10%] w-60 h-60 bg-emerald-500/10 rounded-full blur-3xl"></div>
    <div class="absolute bottom-[-10%] right-[-10%] w-60 h-60 bg-rose-500/10 rounded-full blur-3xl"></div>
    <div class="absolute top-6 right-6 z-20">
      <LanguageSwitcher v-model:currentLang="lang" @update:currentLang="setLang" />
    </div>
    <div class="z-10 w-full max-w-sm mx-auto">
      <div class="text-center mb-10">
        <div class="inline-flex items-center justify-center w-20 h-20 rounded-full bg-slate-800 border-2 border-emerald-500 shadow-[0_0_20px_rgba(16,185,129,0.3)] mb-4">
          <Shield :size="40" class="text-emerald-400" />
        </div>
        <h1 class="text-3xl font-bold text-white tracking-widest">{{ t.appName }}</h1>
        <p class="text-slate-400 text-sm mt-2">{{ t.appSub }}</p>
      </div>
      
      <!-- 错误提示 -->
      <div v-if="errorMessage" class="mb-4 p-3 bg-red-500/10 border border-red-500/30 rounded-lg">
        <p class="text-red-400 text-sm">{{ errorMessage }}</p>
      </div>
      
      <!-- 加载状态 -->
      <div v-if="loading" class="mb-4 text-center">
        <div class="inline-block animate-spin rounded-full h-8 w-8 border-b-2 border-emerald-500"></div>
        <p class="text-slate-400 text-sm mt-2">{{ t.login.loading }}</p>
      </div>
      
      <div class="space-y-4">
        <InputField 
          :icon="User" 
          :placeholder="t.login.accPlaceholder" 
          v-model="account" 
          :disabled="loading"
        />
        <InputField 
          :icon="Lock" 
          :isSecure="true" 
          :placeholder="t.login.passPlaceholder" 
          v-model="password"
          :disabled="loading"
        />
        <div class="relative">
    <InputField 
      :icon="Key" 
      :isSecure="false" 
      :placeholder="t.login.captchaPlaceholder" 
      v-model="captcha"
      :disabled="loading"
    />
    <!-- 驗證碼圖片 -->
    <div class="absolute right-0 top-0 h-full flex items-center pr-3">
      <button 
        type="button"
        @click="refreshCaptcha"
        class="flex items-center justify-center w-24 h-full"
        :disabled="loading"
      >
        <!-- 驗證碼圖片 -->
        <img 
          v-if="captchaImageUrl"
          :src="captchaImageUrl"
          alt="驗證碼"
          class="w-full h-10 object-cover rounded border border-slate-700 hover:border-emerald-500 transition-colors"
          @error="handleCaptchaError"
        />
        <!-- 加載中或錯誤狀態 -->
        <div 
          v-else
          class="w-full h-10 bg-slate-800 border border-slate-700 rounded flex items-center justify-center"
        >
          <template v-if="captchaLoading">
            <div class="animate-spin rounded-full h-4 w-4 border-b-2 border-emerald-500"></div>
          </template>
          <template v-else>
            <RefreshCw :size="16" class="text-slate-500" />
          </template>
        </div>
      </button>
    </div>
  </div>
        <NeonButton 
          fullWidth 
          @click="handleLogin"
          :loading="loading"
          :disabled="loading || !isFormValid"
        >
          {{ t.login.loginBtn }}
        </NeonButton>
        <div class="flex justify-between text-xs text-slate-400 mt-4">
          <button 
            @click="$router.push('/register')" 
            class="hover:text-emerald-400 underline decoration-slate-600"
            :disabled="loading"
          >
            {{ t.login.register }}
          </button>
          <button 
            @click="$router.push('/forgot-password')" 
            class="hover:text-emerald-400 hover:underline decoration-slate-600 transition-all"
            :disabled="loading"
          >
            {{ t.login.forgotPass }}
          </button>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, computed ,watch,onMounted,onUnmounted} from 'vue'
import { useRouter } from 'vue-router'
import { User, Lock, Key, Shield } from 'lucide-vue-next'
import InputField from '@/components/InputField.vue'
import NeonButton from '@/components/NeonButton.vue'
import LanguageSwitcher from '@/components/LanguageSwitcher.vue'
import { useTranslation } from '@/composables/useTranslation'
import { useAuthStore } from '@/stores/auth'
import { showToast } from '@/utils/notification'
import { api } from '@/utils/api'

const router = useRouter()
const authStore = useAuthStore()
const { t, lang, setLang } = useTranslation()

const account = ref('')
const password = ref('')
const captcha = ref('')
const captchaImageUrl = ref('')
const captchaLoading = ref(false)
const captchaKey = ref('')
const loading = ref(false)
const errorMessage = ref('')

// 表单验证
const isFormValid = computed(() => {
  return account.value.trim() && password.value.trim() && captcha.value.trim()
})

// 獲取驗證碼圖片的方法
async function fetchCaptcha() {
  captchaLoading.value = true
  try {
    // 假設 API 端點是 /api/captcha
    const response = await api.get('/auth/captcha', {
      //responseType: 'blob', // 重要：需要設置為 blob 來接收圖片
      params: {
        t: Date.now() // 加上時間戳避免緩存
      }
    })
    
    // 將 blob 轉換為 URL
    //const url = URL.createObjectURL(response.data)
    captchaImageUrl.value = response.data.data.captchaImage
    captchaKey.value = response.data.data.id
    console.log('captchaImageUrl',captchaImageUrl.value)
    
    // 如果有需要，從 response headers 獲取驗證碼 key
    // captchaKey.value = response.headers['x-captcha-key']
    
  } catch (err) {
    console.error('Failed to fetch captcha:', err)
    showToast({
      type: 'error',
      title: t.value.common.error,
      message: t.value.login.captchaLoadFailed || '驗證碼載入失敗'
    })
     
  } finally {
    captchaLoading.value = false
    
  }
}

// 刷新驗證碼
function refreshCaptcha() {
  if (captchaLoading.value) return
  
  // 清理之前的 URL
  if (captchaImageUrl.value) {
    URL.revokeObjectURL(captchaImageUrl.value)
    captchaImageUrl.value = ''
  }
  
  // 重新獲取
  fetchCaptcha()
  
  // 清空輸入的驗證碼
  captcha.value = ''
}

// 處理圖片載入錯誤
function handleCaptchaError() {
  captchaImageUrl.value = ''
  showToast({
    type: 'error',
    title: t.value.common.error,
    message: t.value.login.captchaLoadFailed || '驗證碼圖片載入失敗'
  })
}

async function handleLogin() {
  // 表单验证
  if (!isFormValid.value) {
    errorMessage.value = t.login.validation.allFieldsRequired
    return
  }

  // 清除之前的错误信息
  errorMessage.value = ''
  loading.value = true

  try {
    // 调用登录方法
    const success = await authStore.login({
      account: account.value.trim(),
      password: password.value,
      captcha: captcha.value.trim(),
      captchaKey:captchaKey.value.trim()
    })

    if (success) {
      // 登录成功，显示提示并跳转
      /*showToast({
        type: 'success',
        title: t.value.login.success,
        message: t.value.login.welcomeBack
      })*/
      
      // 跳转到首页或仪表板
      router.push('/dashboard')
    } else {
      // 登录失败，显示错误信息
      errorMessage.value = authStore.error || t.value.login.failed
      await fetchCaptcha()
    }
  } catch (error) {
    console.error('Login error:', error)
    errorMessage.value = t.value.login.networkError
    await fetchCaptcha()
  } finally {
    loading.value = false
  }
}

// 监听输入变化，清除错误信息
function clearError() {
  if (errorMessage.value) {
    errorMessage.value = ''
  }
}

// 为输入框添加监听
watch(account, clearError)
watch(password, clearError)
watch(captcha, clearError)

onMounted(() => {
  fetchCaptcha()
})

// 在組件卸載時清理 URL
onUnmounted(() => {
  if (captchaImageUrl.value) {
    URL.revokeObjectURL(captchaImageUrl.value)
  }
})
</script>
